export default {
    banners:[],
    navList:[],
    le6jiBg:"",
    teseguanBg:"",
    le6ji:[],
    teseguan:[],
    tabBar:[],
    categoryGoods:[],
    hotList:[],
    page:1,
    addressList:[],
    addressCityList:[],
    CityName:"",
}